version: 2

macros:
  - name: mean_absolute_error
    description: |
      Mean Absolute Error (MAE): the average absolute difference between actual and predicted values.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values
      - name: predicted
        type: string
        description: Column name containing the predicted values

  - name: mean_squared_error
    description: |
      Mean Squared Error (MSE): the average squared difference between actual and predicted values.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values
      - name: predicted
        type: string
        description: Column name containing the predicted values

  - name: root_mean_squared_error
    description: |
      Root Mean Squared Error (RMSE): the square root of the mean squared error.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values
      - name: predicted
        type: string
        description: Column name containing the predicted values

  - name: mean_absolute_percentage_error
    description: |
      Mean Absolute Percentage Error (MAPE): the mean absolute percentage difference between actual and predicted values.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values
      - name: predicted
        type: string
        description: Column name containing the predicted values

  - name: r2_score
    description: |
      R-squared: coefficient of determination measuring proportion of variance explained by the predictions.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values
      - name: predicted
        type: string
        description: Column name containing the predicted values

  - name: explained_variance
    description: |
      Explained variance score: proportion of variance explained by the predicted values.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values
      - name: predicted
        type: string
        description: Column name containing the predicted values

  - name: median_absolute_error
    description: |
      Median Absolute Error: the median of absolute differences between actual and predicted values.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values
      - name: predicted
        type: string
        description: Column name containing the predicted values

  - name: mean_bias_error
    description: |
      Mean Bias Error (MBE): average (predicted - actual) indicating systematic over/under prediction.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values
      - name: predicted
        type: string
        description: Column name containing the predicted values

  - name: huber_loss
    description: |
      Huber Loss: a loss function that is quadratic for small errors and linear for large errors,
      making it more robust to outliers than MSE. Uses a threshold delta to transition between
      quadratic and linear loss.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values
      - name: predicted
        type: string
        description: Column name containing the predicted values
      - name: delta
        type: number
        description: Threshold parameter controlling the transition between quadratic and linear loss (default 1.0)

  - name: mean_squared_logarithmic_error
    description: |
      Mean Squared Logarithmic Error (MSLE): measures the mean squared difference between
      the logarithms of predicted and actual values. Useful when targets span several orders
      of magnitude and you care more about relative errors than absolute errors.
      Note: Requires non-negative values for both actual and predicted.
    arguments:
      - name: actual
        type: string
        description: Column name containing the true values (must be non-negative)
      - name: predicted
        type: string
        description: Column name containing the predicted values (must be non-negative)
